# Generated by Django 3.2.4 on 2021-06-26 05:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatRoom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicchatroom',
            name='user',
            field=models.ManyToManyField(blank=True, help_text='users who are connected to chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
