# Generated by Django 3.2.4 on 2021-06-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_parapet_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parapet_User',
        ),
    ]
