# Generated by Django 3.2.4 on 2021-06-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20210610_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='postarticle',
            name='article_pic',
            field=models.ImageField(blank=True, null=True, upload_to='ArticlePictures'),
        ),
    ]
