<<<<<<< HEAD:src/accounts/migrations/0001_initial.py
# Generated by Django 3.2.4 on 2021-07-07 16:19
=======
# Generated by Django 3.2.4 on 2021-07-06 16:48
>>>>>>> Nikhil:Parapet_3/accounts/migrations/0001_initial.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parapet_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('phone', models.CharField(max_length=60, null=True)),
                ('email', models.CharField(max_length=60, null=True)),
                ('username', models.CharField(max_length=60, null=True)),
                ('profile_pic', models.ImageField(default='Profiles/default-profile.jpg', upload_to='Profiles')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('bio', models.CharField(max_length=100, null=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
