# Generated by Django 3.2.4 on 2021-06-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_parapet_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parapet_user',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='Profiles'),
        ),
    ]
