# Generated by Django 3.2.4 on 2021-07-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_parapet_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='parapet_user',
            name='bio',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
