# Generated by Django 3.2.4 on 2021-07-02 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_parapet_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='parapet_user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
