# Generated by Django 3.2.4 on 2021-07-05 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_parapet_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='parapet_user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
