# Generated by Django 3.2.4 on 2021-06-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_parapet_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parapet_user',
            name='profile_pic',
            field=models.ImageField(default='static/media/default-profile.jpg', upload_to=''),
        ),
    ]
