# Generated by Django 3.2.4 on 2021-06-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_parapet_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='parapet_user',
            name='username',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
