# Generated by Django 3.2.4 on 2021-06-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_parapet_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parapet_user',
            name='profile_pic',
            field=models.ImageField(default='Profiles/default-profile', upload_to='Profiles'),
        ),
    ]
